name: infof308-chrono
channels:
  - https://conda.anaconda.org/intel
  - https://conda.anaconda.org/projectchrono
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/pytorch
dependencies:
  - python=3.9
  - numpy=1.24
  - irrlicht=1.8
  - pychrono=7.0
  - loguru=0.6
  - pytorch
  - mkl
  - stable-baselines3=1.5 
  - gymnasium=0.27.1
  - tqdm=4.65.0
  - rich=13.3.2
  - pip
  - pip:
    - pygad==2.19.1
    - black~=22.12
    - isort~=5.11
    - git+https://github.com/DLR-RM/stable-baselines3@feat/gymnasium-support
    - git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib@feat/gymnasium-support
